# Generated by Django 4.2.7 on 2024-02-18 07:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Car",
        ),
    ]
